name: Deploy data to S3 Production

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths: ["data/**", ".github/workflows/deploy-data-to-s3-production.yml"]

env:
  AWS_REGION: ca-central-1
  S3BUCKET: critical-editions-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy data to S3 bucket
        run: |
          aws s3 sync ./data s3://${{ env.S3BUCKET }}/data --delete
      - name: Invalidating Cloudfront Cache
        run: |
          aws cloudfront create-invalidation ./data s3://${{ env.S3BUCKET }}/data
